GET http://localhost/feedbackelf/feedbackelf-api/php/api/api.php/product/24/bugs
Content-Type: application/json
App_id: 32565545-391f-11f0-a81e-1a220d8ac2c9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOm51bGwsInN1YiI6bnVsbCwiYXVkIjpudWxsLCJleHAiOjE4MTA3OTk5NjIsIm5iZiI6MTc1MDMxOTk2MiwiaWF0IjoxNzUwMzE5OTYyLCJqdGkiOiJ7NzdBNzBCOEQtMUM0OS1EQkM3LTQwM0EtRTI4NjFBQ0Y1MzUwfSIsImRhdGEiOnsiaWQiOjE1MDMsInVzZXJuYW1lIjpudWxsLCJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJyb2xlIjpudWxsLCJwZXJtaXNzaW9ucyI6W119fQ.ZjEwMWNjZDA5OTQ1N2E1YWE2ODgxYmQ1ODljZTBiMjZlM2E4NjY1MWZlOTU0ODU2MTc5NWM5NTQ1NTI4NDY2Ng